# Generated by Django 3.1.6 on 2024-07-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20240711_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Printer', 'Printer'), ('Software', 'Software'), ('Vacations', 'Vacations'), ('Peripherals', 'Peripherals'), ('Recovery', 'Recovery'), ('VPN', 'VPN'), ('Network', 'Network'), ('Server', 'Server'), ('Database', 'Database'), ('Collaboration', 'Collaboration'), ('Budgeting', 'Budgeting'), ('Reporting', 'Reporting'), ('Consultation', 'Consultation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
