# Generated by Django 5.0.6 on 2024-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_attachment_id_alter_comment_id_alter_log_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='mensajito',
            field=models.CharField(default='We got your back, {self.owner}! ;)', max_length=300),
        ),
    ]
